### ISSUE TITLE
how do i install this

### ISSUE THREAD

**Issue by reeeeenooooowhyyyy** [sc2ad/QuestPackageManager#21]
pls dont ignore me i want to know how do i install this PLS

**Comment by WaffleTheCool** [comment]
This should work, https://github.com/sc2ad/QuestPackageManager/suites/3726955417/artifacts/91231627 (I do not say it will work, just say it should)

**Comment by sc2ad** [comment]
Superseded by #28

**Comment by reeeeenooooowhyyyy** [comment]
Hallo jeg vilt så hvem er du
