### ISSUE TITLE
qpm is not recognized as internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Goldngamr5** [sc2ad/QuestPackageManager#8]
I would like to use qpm to make beat saber mods, but I don't know how to get it working. I downloaded the files and tried to run 'qpm package create' but command prompt just keeps saying qpm is not a thing. can anyone help me get it working?

**Comment by sc2ad** [comment]
Hi there! Have you tried adding the downloaded folder (from GH actions) to your PATH?

**Comment by Goldngamr5** [comment]
How would I do/check that again?

**Comment by Goldngamr5** [comment]
> Hi there! Have you tried adding the downloaded folder (from GH actions) to your PATH?

How would I do/check that again?
